classdef unConstrained < handle
    
    properties
        funName='';
        xMin=[];
        xMax=[];
        dim=0;
        locMinZ
        locMinX
        globMinZ
        globMinX
        Xeval
    end
    
    methods
        function obj=unConstrained(funName,XX,dim)
            addpath('unConstrained/');
            if nargin==0
                obj.checkAllfun();
            else
            obj.funName=funName;
            obj.dim=loadDim(funName);
            end
            if nargin==1
                obj.demo
                obj.checkFun(obj.funName);
            elseif nargin==2
                obj.prepX(XX);
                obj.eval()
            elseif nargin==3
                obj.dim=dim;
                obj.prepX(XX);
                obj.eval()
            end
        end
        %setters
        function set.funName(obj,txt)
            %if the function is available we store it
            if availableFun(txt)
                obj.funName=txt;
            else
                fprintf('Test function %s unavailable \n',txt);
                dispAvailableFun();
            end
        end
        function prepX(obj,XX)
            sX=[size(XX,1) size(XX,2) size(XX,3)];
            nbvar=sX(3);
            if isinf(obj.dim)
                if nbvar==1
                    obj.Xeval=reshape(XX,[],1,sX(2));
                else
                    obj.Xeval=XX;
                    obj.dim=nbvar;
                end
            else
                if nbvar==obj.dim
                    obj.Xeval=XX;
                elseif nbvar==1
                    if sX(2)==obj.dim
                        obj.Xeval=reshape(XX,[],1,sX(2));
                    else
                        fprintf('Wrong size of sample points\n');
                    end
                else
                    fprintf('Wrong size of sample points\n');
                end
            end
        end
        function [ZZ,GZ]=eval(obj,XX)
            if nargin==1
                [ZZ,GZ]=feval(['fun' obj.funName],obj.Xeval);
            else
                [ZZ,GZ]=feval(['fun' obj.funName],XX);
            end
        end
        %dem mode
        function demo(obj)
            if isinf(obj.dim);obj.dim=2;end
            if obj.dim==1
            elseif obj.dim==2||isinf(obj.dim)
                stepM=50;
                [Xmin,Xmax]=loadSpace(obj.funName,obj.dim);
                xL=linspace(Xmin(1),Xmax(1),stepM);
                yL=linspace(Xmin(2),Xmax(2),stepM);
                [x,y]=meshgrid(xL,yL);
                xx=zeros(stepM,stepM,2);
                xx(:,:,1)=x;xx(:,:,2)=y;
                %evaluation of the function
                [ZZ,GZ]=obj.eval(xx);
                %display
                obj.show2D(x,y,ZZ,GZ);
            else
                fprintf('Too large dimension to be plotted');
            end
        end
        %check function by checking minimum
        function isOk=checkFun(obj,funName)
            isOk=true;
            [X,Z]=loadGlobMin(funName,obj.dim);
            obj.prepX(X);
            ZZ=obj.eval();
            if abs(ZZ(:)-Z(:))>1e-6;
                fprintf('Issue with the %s function (wrong minimum obtained)\n',funName);
                fprintf('Obtained:');fprintf('%d ',ZZ);
                fprintf('Expected:');fprintf('%d ',Z);
                isOk=false;
            end
        end
        %check all functions
        function isOk=checkAllfun(obj)
            isOk=true;
            %extract name of functions
            strFun=loadDim();
            listFun=fieldnames(strFun);
            %check every function
            for itF=1:numel(listFun)
                listFun{itF}
                isOk=isOk&&obj.checkFun(listFun{itF});
            end
        end
        %show 2D function 
        function show2D(obj,XX,YY,ZZ,GZ)
            nbR=2;
            nbC=3;
            figure
            subplot(nbR,nbC,1)
            surf(XX,YY,ZZ);
            axis('tight','square')
            xlabel('x'), ylabel('y'), title(obj.funName)
            subplot(nbR,nbC,2)
            surf(XX,YY,GZ(:,:,1));
            axis('tight','square')
            xlabel('x'), ylabel('y'), title(['Grad. X ' obj.funName])
            subplot(nbR,nbC,3)
            surf(XX,YY,GZ(:,:,2));
            axis('tight','square')
            xlabel('x'), ylabel('y'), title(['Grad. Y ' obj.funName])
            %
            subplot(nbR,nbC,4)
            contour(XX,YY,ZZ);
            axis('tight','square')
            xlabel('x'), ylabel('y'), title(obj.funName)
            subplot(nbR,nbC,5)
            contour(XX,YY,GZ(:,:,1));
            axis('tight','square')
            xlabel('x'), ylabel('y'), title(['Grad. X ' obj.funName])
            subplot(nbR,nbC,6)
            contour(XX,YY,GZ(:,:,2));
            axis('tight','square')
            xlabel('x'), ylabel('y'), title(['Grad. Y ' obj.funName])
        end
    end
    
end


%function for checking if the function is available
function funOk=availableFun(txt)
%extract name of functions
strFun=loadDim();
listFun=fieldnames(strFun);
%check if function is available
funOk=any(ismember(listFun,txt));
end

%display available testfunctions
function funOk=dispAvailableFun()
%extract name of functions
strFun=loadDim();
listFun=fieldnames(strFun);
%check if function is available
fprintf('=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=\n');
fprintf('Available techniques for surrogate models\n');
dispTableTwoColumns(obj.typeAvail,obj.typeTxt);
fprintf('=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=\n');
end

%load dimension
function dim=loadDim(funName)
listDim=struct(...
    'Brown',Inf,...
    'Bukin1',2,...
    'Bukin2',2,...
    'Bukin3',2,...
    'Bukin4',2,...
    'Bukin5',2,...
    'Bukin6',2,...
    'Bukin7',2,...
    'Bukin8',2,...
    'Bukin9',2,...
    'Bukin10',2,...
    'Bukin11',2,...
    'Bukin12',2,...
    'Bukin13',2,...
    'Bukin14',2,...
    'Bukin15',2,...
    'Bukin16',2,...
    'Bukin17',2,...
    'Bukin18',2,...
    'Bukin19',2,...
    'Bukin20',2,...
    'ThreeHump',2,...
    'SixHump',2,...
    'ChenV',2,...
    'ChenBird',2,...
    'Chichinadze',2,...
    'ChungReynolds',Inf,...
    'Cola',17,...
    'Colville',4,...
    'Corana',4,...
    'CosineMixture',Inf,...
    'CrossInTray',2,...
    'Csendes',Inf,...
    'Cube',2,...
    'Damavandi',2,...
    'Deb1',Inf,...
    'Deb2',Inf,...
    'Deb3',Inf,...
    'Deb4',Inf,...
    'DeckkersAarts',2,...
    'prout',5);
if nargin==1
    dim=listDim.(funName);
else
    dim=listDim;
end
end

%load global minima
function [GlobX,GlobZ]=loadGlobMin(funName,dim)
listGlobXmin=struct(...
    'Brown',0,...
    'Bukin1',[1,-1;-1,1],...
    'Bukin2',[-10,0],...
    'Bukin3',[-1.5*pi,0],...
    'Bukin4',[-10,0],...
    'Bukin5',[-10,0],...
    'Bukin6',[-10,1],...
    'Bukin7',[-5,5;142.574,-0.17535],...
    'Bukin8',[-20,-20],...
    'Bukin9',[-6,-3],...
    'Bukin10',[-7,-9;-9,-3],...
    'Bukin11',[-5,-5],...
    'Bukin12',[-5,-5],...
    'Bukin13',[-3,0.5],...
    'Bukin14',[-10,-1],...
    'Bukin15',[-10,25;10,-175],...
    'Bukin16',[-5,-5],...
    'Bukin17',[-5,-5;20,-30],...
    'Bukin18',[-5,-5;2.28916,-128.91566],...
    'Bukin19',[9,71;-8,54],...
    'Bukin20',[-2,-1],...
    'ThreeHump',[0,0],...
    'SixHump',[-0.0898, 0.7126;0.0898,-0.7126],...
    'ChenV',[7/18,13/18],...
    'ChenBird',[1/2,1/2;-1/2,-1/2],...
    'Chichinadze',[6.189866586965680,0.5],...
    'ChungReynolds',0,...
    'Cola',[0.651906,1.30194,0.099242,-0.883791,...
    -0.8796,0.204651,-3.28414,0.851188,-3.46245,...
    2.53245,-0.895246,0.204651,-3.28414,0.851188,...
    -3.46245,2.53245,-0.895246,1.40992,-3.07367,...
    1.96257,-2.97872,-0.807849,-1.68978],...
    'Colville',[1,1,1,1],...
    'Corana',[0,0,0,0],...
    'CosineMixture',0,...
    'CrossInTray',[1.349406685353340,1.349406608602084;...
    -1.349406685353340,1.349406608602084;...
    1.349406685353340,-1.349406608602084;...
    -1.349406685353340,-1.349406608602084],...
    'Csendes',0,...
    'Cube',[1,1],...
    'Damavandi',[2,2],...
    'Deb1',NaN,...
    'Deb2',NaN,...
    'Deb3',NaN,...
    'Deb4',NaN,...
    'DeckkersAarts',[0,-15;0,15],...
    'prout',0);
listGlobZmin=struct(...
    'Brown',0,...
    'Bukin1',[0;0],...
    'Bukin2',0,...
    'Bukin3',0,...
    'Bukin4',0,...
    'Bukin5',0,...
    'Bukin6',0,...
    'Bukin7',[0;0],...
    'Bukin8',0,...
    'Bukin9',0,...
    'Bukin10',[0;0],...
    'Bukin11',0,...
    'Bukin12',0,...
    'Bukin13',0,...
    'Bukin14',0,...
    'Bukin15',[0;0],...
    'Bukin16',0,...
    'Bukin17',[0;0],...
    'Bukin18',[0;0],...
    'Bukin19',[0;0],...
    'Bukin20',0,...
    'ThreeHump',0,...
    'SixHump',[-1.0316;-1.0316],...
    'ChenV',-2000,...
    'ChenBird',[-2000;2000],...
    'Chichinadze',-42.94438701899098,...
    'ChungReynolds',0,...
    'Cola',11.7464,...
    'Colville',0,...
    'Corana',0,...
    'CosineMixture',0.1*dim,...
    'CrossInTray',ones(1,4)*(-2.06261218),...
    'Csendes',0,...
    'Cube',0,...
    'Damavandi',0,...
    'Deb1',NaN,...
    'Deb2',NaN,...
    'Deb3',NaN,...
    'Deb4',NaN,...
    'DeckkersAarts',-24777.109,...
    'prout',0);

lGX=listGlobXmin.(funName);
GlobZ=listGlobZmin.(funName);
if size(lGX,2)==1
    GlobX=repmat(lGX,[1,dim]);
else
    GlobX=lGX;
end
end

%load space definition
function [xMin,xMax]=loadSpace(funName,dim)
listSpace=struct(...
    'Brown',[-1;4],...
    'Bukin1',[-5 -5;5 5],...
    'Bukin2',[-15 -3;-5 3],...
    'Bukin3',[-5 -5;5 5],...
    'Bukin4',[-15 -5;5 5],...
    'Bukin5',[-15 -5;5 5],...
    'Bukin6',[-5 -5;5 5],...
    'Bukin7',[-5 -5;150 5],...
    'Bukin8',[-25 -25;0 0],...
    'Bukin9',[-10 -5;5 5],...
    'Bukin10',[-10 -10;0 0],...
    'Bukin11',[-10 -10;0 0],...
    'Bukin12',[-10 -10;0 0],...
    'Bukin13',[-5 -5;5 5],...
    'Bukin14',[-15 -5;5 5],...
    'Bukin15',[-30 -200;15 100],...
    'Bukin16',[-40 -40;40 40],...
    'Bukin17',[-40 -40;40 40],...
    'Bukin18',[-10 -150;10 10],...
    'Bukin19',[-30 -30;30 150],...
    'Bukin20',[-5 -5;5 5],...
    'ThreeHump',[-5 -5;5 5],...%[-2.5 -3;2.5 3]
    'SixHump',[-3 -2;3 2],...%[-2 -1;2 1]
    'ChenV',[-500;500],...
    'ChenBird',[-500;500],...
    'Chichinadze',[-30;30],...
    'ChungReynolds',[-100;100],...
    'Cola',[0,-4*ones(1,16);4*ones(1,17)],...
    'Colville',[-10;10],...
    'Corana',[-500;500],...
    'CosineMixture',[-1;1],...
    'CrossInTray',[-10;10],...
    'Csendes',[-1;1],...
    'Cube',[-10;10],...
    'Damavandi',[0;14],...
    'Deb1',[-1;1],...
    'Deb2',[-1;1],...
    'Deb3',[0;1],...
    'Deb4',[0;1],...
    'DeckkersAarts',[-20;20],...
    'prout',[0;14]);

spaceL=listSpace.(funName);
if size(spaceL,2)==1
    xMin=ones(1,dim)*spaceL(1);
    xMax=ones(1,dim)*spaceL(2);
else
    xMin=spaceL(1,:);
    xMax=spaceL(2,:);
end
end

%function display table with two columns of text
function dispTableTwoColumns(tableA,tableB)
%size of every components in tableA
sizeA=cellfun(@numel,tableA);
maxA=max(sizeA);
%space after each component
spaceA=maxA-sizeA+3;
spaceTxt=' ';
%display table
for itT=1:numel(tableA)
    Gfprintf('%s%s%s\n',tableA{itT},spaceTxt(ones(1,spaceA(itT))),tableB{itT});
end
end


