Description of listPb
listPb
PURPOSE
% extract list of problems
SYNOPSIS
function l=listPb(typePb)
DESCRIPTION
% extract list of problems
CROSS-REFERENCE INFORMATION
This function calls:
loadProbCons % function for loading constrained problems
loadProbMulti % Function for loading available multi-objective problems
loadDimUn % function for loading dimension of available functions
This function is called by:
checkAllPb % Method of optiGTest class
loadProbCons % function for loading constrained problems
loadProbMulti % Function for loading available multi-objective problems
SOURCE CODE
%% extract list of problems
function l=listPb(typePb)
if nargin==0;typePb='';end
switch typePb
    case {'UnConstrained','Un','un','Unconstrained','unconstrained'}
        strPb=loadDimUn();
        l=fieldnames(strPb);
    case {'Constrained','Cons','cons','constrained'}
        strPb=loadProbCons();
        %
        l=fieldnames(strPb);
    case {'MultiObj','Multi','multi','Multiobj','multiobj'}
        strPb=loadProbMulti();
        %
        l=fieldnames(strPb);
    otherwise
        strPbUn=loadDimUn();
        strPbCons=loadProbCons();
        strPbMulti=loadProbMulti();
        %
        listPbUn=fieldnames(strPbUn);
        listPbCons=fieldnames(strPbCons);
        listPbMulti=fieldnames(strPbMulti);
        %
        l=vertcat(listPbUn,listPbCons,listPbMulti);
end
end