Description of loadDimMulti
loadDimMulti
PURPOSE
% function for loading dimension of available multi-objective problems
SYNOPSIS
function dim=loadDimMulti(funName)
DESCRIPTION
% function for loading dimension of available multi-objective problems
 L. LAURENT --  04/05/2018 -- luc.laurent@lecnam.net
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
funMD % Method of optiGTest class
availablePb % Function for checking if the function is available
pictures %%% Create pitcures for all cases
SOURCE CODE
%% function for loading dimension of available multi-objective problems
% L. LAURENT --  04/05/2018 -- luc.laurent@lecnam.net
% sources available here:
% https://bitbucket.org/luclaurent/optigtest/
% https://github.com/luclaurent/optigtest/
% optiGTest - set of testing functions    A toolbox to easy manipulate functions.
% Copyright (C) 2018  Luc LAURENT <luc.laurent@lecnam.net>
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>.
function dim=loadDimMulti(funName)
listDim=struct(...
        'BinhKorn',2,...
    'ChakongHaimes',2,...
    'FonsecaFleming',Inf,...
    'TestFun4',2,...
    'Kursawe',3,...
    'MultiSchaffer1',1,...
    'MultiSchaffer2',1,...
    'Poloni',2,...
    'ZitzlerDebThiele1',30,...
    'ZitzlerDebThiele2',30,...
    'ZitzlerDebThiele3',30,...
    'ZitzlerDebThiele4',10,...
    'ZitzlerDebThiele6',10,...
    'OsyczkaKundu',6,...
    'CTP1',2,...
    'ConstrEx',2,...
    'Viennet',2);
if nargin==1
    dim=listDim.(funName);
else
    dim=listDim;
end
end